### ISSUE TITLE
集群模式下，在所有节点的mosquitto.conf中都要写上所有节点的信息吗

### ISSUE THREAD

**Issue by xiangwangcheng** [hui6075/mosquitto-cluster#19]
例如有三个broker节点brokerA brokerB brokerC。
在每个节点的conf中都要配置一下信息吗：
node_name brokerA
node_address 192.168.1.101:1883

node_name brokerB
node_address 192.168.1.102:1883

node_name brokerC
node_address 192.168.1.103:1883

还是每个节点只配置自己的?

**Comment by hui6075** [comment]
每个节点都配上所有的节点
