### ISSUE TITLE
怎么清空缓存数据

### ISSUE THREAD

**Issue by houmingbo** [hui6075/mosquitto-cluster#23]
您好，之前使用mosquitto的桥接模式，本地节点桥接的是云服务上的节点，应用场景原因，本地节点会经常和云服务网络断开，当再此连接时，会将断开期间的数据全部发出，这个断开期间可能时几个小时。这样大量数据就会堵在里面。如何在断开连接时，将数据清除？

**Comment by hui6075** [comment]
桥接的问题，可以去原mosquitto仓问问作者哈~
