### ISSUE TITLE
How to install and start mosquitto cluster? Is there any detailed documentation

### ISSUE THREAD

**Issue by Jack-he1233** [hui6075/mosquitto-cluster#24]
@hui6075 
1. How to configure the load balancer?
2. Where are the ip and port of each node configured

**Comment by hui6075** [comment]
@Jack-he1233 installation:
> git clone https://github.com/hui6075/mosquitto-cluster.git
> cd mosquitto-cluster && vi config.mk

# WITH_BRIDGE:=yes
WITH_CLUSTER:=yes
> make && make install

**Comment by hui6075** [comment]
@Jack-he1233 1.for load balance, depend on which you're using. for example, nginx has it's configuration. 2.vi mosquitto.conf;node_name node1
node_address 192.168.1.1:1883

node_name node2
node_address 192.168.1.2:1883.

Did you read the readme?
