### ISSUE TITLE
make install不通过 

### ISSUE THREAD

**Issue by fsfnt041** [hui6075/mosquitto-cluster#4]
cc -Wall -ggdb -O2  -I. -I.. -I../lib  -DVERSION="\"1.5.0\"" -DWITH_BROKER -DWITH_TLS -DWITH_TLS_PSK -DWITH_UUID -DWITH_CLUSTER -DWITH_PERSISTENCE -DWITH_MEMORY_TRACKING -DWITH_SYS_TREE -DWITH_EC -DWITH_EPOLL -c handle_connect.c -o handle_connect.o
handle_connect.c:33:25: fatal error: uuid/uuid.h: No such file or directory
 #  include <uuid/uuid.h>
                         ^
compilation terminated.
make[1]: *** [handle_connect.o] Error 1
make[1]: Leaving directory `/mosquitto/mosquitto-cluster/src'

**Comment by fsfnt041** [comment]
123

**Comment by Yukino0319** [comment]
Centos系统下
```
yum install e2fsprogs-devel
yum install uuid-devel
yum install libuuid-devel
```

其他系统使用相关方式安装环境

**Comment by hui6075** [comment]
@Yukino0319 谢谢
