### ISSUE TITLE
请问这是基于Mosquitto哪个版本开发的呢？

### ISSUE THREAD

**Issue by lincoln24** [hui6075/mosquitto-cluster#5]
我现在在研究mosquitto 1.5.5，发现该版本已经改进了许多以前的弊病
比如加入epoll，订阅树引入hash表等等
请问您所开发的集群有没有把这些新特性包括在内呢？

**Comment by hui6075** [comment]
set (VERSION 1.5.0)
我过几天同步一下代码。最近太忙了。我这个版本是有epoll的，但这个epoll做的并不好。订阅数也是有HASH的。
